// 在隔离的 CODEX_HOME 和应用数据目录中验证真实 Electron 页面与预加载接口。
const { app, BrowserWindow, dialog } = require('electron')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')

const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'codex-manager-memory-ui-'))
const codex = path.join(sandbox, 'codex')
const memory_root = path.join(codex, 'memories')
const app_data = path.join(sandbox, 'app-data')
const bootstrap = path.join(sandbox, 'bootstrap')
for (const folder of [app_data, bootstrap, memory_root, path.join(memory_root, 'rollout_summaries')]) fs.mkdirSync(folder, { recursive: true })
app.setPath('appData', app_data); app.setPath('userData', bootstrap); app.setPath('sessionData', bootstrap)
process.env.CODEX_HOME = codex
fs.writeFileSync(path.join(codex, 'config.toml'), '[features]\nmemories = true\n[memories]\nuse_memories = true\n')
const summary_path = path.join(memory_root, 'memory_summary.md')
const original_summary = '\uFEFF# 记忆总览\r\n\r\n中文读取验证。这是隔离测试目录中的示例记忆。\r\n\r\n## 用户偏好\r\n\r\n- 使用简体中文解释实现与验证结果。\r\n- 优先保持现有界面和项目约定。\r\n- 修改前核查来源，保留可恢复的原始内容。\r\n\r\n## 当前项目\r\n\r\nCodex Manager 是本地管理工作台，支持分类浏览、全文搜索和安全维护记忆文件。\r\n\r\n## 最近任务\r\n\r\n完成读取服务、三栏工作台与备份恢复的隔离验证。\r\n\r\n![禁止自动加载](https://example.invalid/private-memory.png)\r\n\r\n<script>window.memory_injected = true</script>\r\n\r\n' + '这是用于验证独立滚动的记忆段落。\r\n\r\n'.repeat(80)
fs.writeFileSync(summary_path, original_summary)
fs.writeFileSync(path.join(memory_root, 'MEMORY.md'), '# 长期规则\n\n只删除当前文件，不影响摘要。\n')
fs.writeFileSync(path.join(memory_root, 'other.json'), '{"说明":"仅查看元数据"}')
fs.writeFileSync(path.join(memory_root, 'large.txt'), '# 大文件测试\n\n' + '分段只读内容中文🙂\n'.repeat(90000))
for (let index = 0; index < 70; index++) fs.writeFileSync(path.join(memory_root, 'rollout_summaries', `rollout-${index}.md`), `# 会话总结 ${index}\n\n常规上下文。\n${index === 42 ? '正文末尾唯一检索命中。' : ''}`)
dialog.showMessageBox = async () => ({ response: 0 })
let exit_prompts = 0
dialog.showMessageBoxSync = () => { exit_prompts++; return 0 }
// 提前退出必须作为失败报告，不能将进程退出码零误当成验收通过。
app.on('will-quit', event => { event.preventDefault(); console.error('测试尚未完成时应用意外退出'); app.exit(1) })
const results = []
const report_root = path.resolve(__dirname, '../reports')
const timeout = setTimeout(() => { console.error('记忆页面验证超时'); app.exit(2) }, 180000)

app.once('browser-window-created', (_event, window) => {
  const console_errors = []
  window.webContents.on('console-message', event => { if (event.level === 'error') console_errors.push(event.message) })
  window.webContents.once('did-finish-load', async () => {
    const run = code => window.webContents.executeJavaScript(code, true)
    const until = async (code, label = code) => {
      for (let attempt = 0; attempt < 240; attempt++) {
        if (await run(code)) return
        await new Promise(resolve => setTimeout(resolve, 50))
      }
      throw new Error(`等待失败：${label}`)
    }
    const check = async (name, work) => { await work(); results.push(name); console.log(`通过：${name}`) }
    const click = (text, scope = 'document') => run(`(() => { const button = [...${scope}.querySelectorAll('button')].find(item => item.getClientRects().length && item.textContent.trim() === ${JSON.stringify(text)}); if (!button || button.disabled) throw Error('按钮不可用：' + ${JSON.stringify(text)}); button.click() })()`)
    const input = (label, value) => run(`(() => { const element = document.querySelector('[aria-label=' + ${JSON.stringify(JSON.stringify(label))} + ']'); if (!element) throw Error('输入框不存在'); const setter = Object.getOwnPropertyDescriptor(element.tagName === 'TEXTAREA' ? HTMLTextAreaElement.prototype : HTMLInputElement.prototype, 'value').set; setter.call(element, ${JSON.stringify(value)}); element.dispatchEvent(new Event('input', { bubbles: true })); })()`)
    const select_file = relative_path => run(`document.querySelector('[data-memory-path=' + ${JSON.stringify(JSON.stringify(relative_path))} + ']').click()`)
    const idle = () => until(`document.querySelector('.memories-page')?.getAttribute('aria-busy') === 'false'`)
    const confirm = text => click(text, `document.querySelector('.confirm-dialog')`)
    const editor_text = () => run(`document.querySelector('[aria-label="记忆编辑器"]')?.value`)
    try {
      window.setContentSize(1600, 960)
      await until(`!!document.querySelector('nav button[aria-label="记忆管理"]')`)
      await run(`document.querySelector('nav button[aria-label="记忆管理"]').click()`)
      await until(`document.querySelector('.memory-detail h2')?.textContent === '记忆总览'`)
      await idle()
      await check('默认摘要与配置只读状态', async () => {
        assert.equal(await run(`document.querySelector('.memory-location').textContent.includes(${JSON.stringify(memory_root)})`), true)
        assert.equal(await run(`document.querySelectorAll('.memory-file').length`), 74)
        assert.equal(await run(`document.querySelectorAll('.memory-config input').length`), 0)
        assert.equal(await run(`document.querySelector('.memory-config').textContent.includes('不代表当前运行状态')`), true)
      })
      await check('Markdown 不执行 HTML 或加载远程图片', async () => {
        assert.equal(await run(`document.querySelectorAll('.memory-body img, .memory-body script').length`), 0)
        assert.equal(await run(`window.memory_injected === undefined`), true)
        assert.equal(await run(`document.querySelector('.memory-body').textContent.includes('禁止自动加载')`), true)
      })
      await check('列表和正文独立滚动，键盘调整分隔线', async () => {
        assert.ok(await run(`document.querySelector('.memory-list > .search-field').getBoundingClientRect().height <= 52`), '搜索框不能继承弹性扩张占据列表高度')
        const dimensions = await run(`['.memory-file-scroll', '.memory-body'].map(selector => {const e=document.querySelector(selector); return [e.scrollHeight,e.clientHeight,getComputedStyle(e).overflowY]})`)
        for (const [height, client, overflow] of dimensions) { assert.ok(height > client); assert.match(overflow, /auto|scroll/) }
        const before = await run(`document.querySelector('.memory-list').getBoundingClientRect().width`)
        await run(`document.querySelectorAll('.memory-divider')[1].dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowRight',bubbles:true}))`)
        await until(`Math.abs(document.querySelector('.memory-list').getBoundingClientRect().width - ${before}) > 5`)
      })
      await check('标题路径和正文全文搜索显示命中片段', async () => {
        await input('搜索记忆', '正文末尾唯一')
        await until(`document.querySelectorAll('.memory-file').length === 1 && document.querySelector('.memory-file').textContent.includes('正文末尾唯一')`)
        await input('搜索记忆', 'rollout-42.md')
        await until(`document.querySelectorAll('.memory-file').length === 1 && document.querySelector('.memory-file')?.getAttribute('data-memory-path') === 'rollout_summaries/rollout-42.md'`)
        await input('搜索记忆', '')
        await until(`document.querySelectorAll('.memory-file').length === 74`)
      })
      await check('未保存草稿在切文件、刷新和离页时保留', async () => {
        await click('编辑'); await input('记忆编辑器', '# 修改草稿\n\n保存到真实测试文件。')
        await select_file('MEMORY.md'); await until(`!!document.querySelector('.confirm-dialog')`)
        assert.equal(await run(`document.activeElement?.textContent`), '取消')
        await confirm('取消'); await idle(); assert.match(await editor_text(), /修改草稿/)
        await click('刷新'); await until(`!!document.querySelector('.confirm-dialog')`); await confirm('取消'); await idle()
        await run(`document.querySelector('nav button[aria-label="账号管理"]').click()`)
        await until(`!!document.querySelector('.confirm-dialog')`); await confirm('取消')
        assert.match(await editor_text(), /修改草稿/)
      })
      await check('关闭窗口与退出应用取消后草稿仍保留', async () => {
        const settings = await run('window.codexAccounts.getSettings()')
        await run(`window.codexAccounts.saveSettings(${JSON.stringify({ ...settings.data, minimizeToTray: false })})`)
        window.close()
        for (let attempt = 0; attempt < 100 && exit_prompts < 1; attempt++) await new Promise(resolve => setTimeout(resolve, 50))
        assert.equal(exit_prompts, 1)
        assert.equal(window.isDestroyed(), false)
        assert.match(await editor_text(), /修改草稿/)
        app.quit()
        for (let attempt = 0; attempt < 100 && exit_prompts < 2; attempt++) await new Promise(resolve => setTimeout(resolve, 50))
        assert.equal(exit_prompts, 2)
        assert.match(await editor_text(), /修改草稿/)
      })
      await check('Ctrl+S 保存并保留 BOM 与 CRLF，创建可读备份', async () => {
        await run(`window.dispatchEvent(new KeyboardEvent('keydown',{key:'s',ctrlKey:true,bubbles:true}))`)
        await idle(); await until(`document.querySelector('.memory-notice')?.textContent.includes('已保存本地记忆')`)
        assert.equal(fs.readFileSync(summary_path, 'utf8'), '\uFEFF# 修改草稿\r\n\r\n保存到真实测试文件。')
        await click('备份'); await idle()
        await click('查看', `document.querySelector('.memory-backup-row')`); await idle()
        assert.equal(await run(`document.querySelector('.memory-backup-preview').textContent.includes('中文读取验证')`), true)
        await click('恢复', `document.querySelector('.memory-backup-row')`)
        await until(`!!document.querySelector('.confirm-dialog')`); await confirm('恢复备份'); await idle()
        assert.equal(fs.readFileSync(summary_path, 'utf8'), original_summary)
        await run(`document.querySelector('[aria-label="关闭记忆备份"]').click()`)
      })
      await check('外部修改时拒绝覆盖，页面保留草稿', async () => {
        await click('编辑'); await input('记忆编辑器', '必须保留的草稿')
        fs.writeFileSync(summary_path, '# 外部更新\n\n并发变化')
        await click('保存'); await idle()
        assert.equal(fs.readFileSync(summary_path, 'utf8'), '# 外部更新\n\n并发变化')
        assert.equal(await editor_text(), '必须保留的草稿')
        assert.equal(await run(`document.querySelector('.memory-notice.error')?.textContent.includes('修改')`), true)
        await click('取消编辑'); await until(`!!document.querySelector('.confirm-dialog')`); await confirm('放弃更改'); await idle()
        await click('刷新'); await idle()
      })
      await check('新增人工补充的写入位置及保存提示', async () => {
        await click('新增记忆'); await idle(); await input('新记忆标题', '用户偏好'); await input('记忆编辑器', '以后使用中文解释。')
        await click('保存'); await idle()
        await until(`document.querySelector('.memory-detail h2')?.textContent === '用户偏好'`)
        const notes = fs.readdirSync(path.join(memory_root, 'extensions', 'ad_hoc', 'notes'))
        assert.equal(notes.length, 1)
        assert.equal(fs.readFileSync(path.join(memory_root, 'extensions', 'ad_hoc', 'notes', notes[0]), 'utf8'), '# 用户偏好\n\n以后使用中文解释。\n')
        assert.equal(await run(`document.querySelector('.memory-notice').textContent.includes('后续整合')`), true)
      })
      await check('删除取消、单文件删除与备份恢复', async () => {
        await select_file('MEMORY.md'); await idle(); await click('删除'); await until(`!!document.querySelector('.confirm-dialog')`)
        await confirm('取消'); await idle(); assert.ok(fs.existsSync(path.join(memory_root, 'MEMORY.md')))
        await click('删除'); await until(`!!document.querySelector('.confirm-dialog')`); await confirm('删除记忆文件'); await idle()
        assert.equal(fs.existsSync(path.join(memory_root, 'MEMORY.md')), false)
        assert.equal(fs.existsSync(summary_path), true)
        await click('备份'); await idle()
        const selector = `[...document.querySelectorAll('.memory-backup-row')].find(row=>row.textContent.includes('MEMORY.md'))`
        await click('恢复', selector); await until(`!!document.querySelector('.confirm-dialog')`); await confirm('恢复备份'); await idle()
        assert.equal(fs.readFileSync(path.join(memory_root, 'MEMORY.md'), 'utf8').includes('只删除当前文件'), true)
        await click('删除备份', selector); await until(`!!document.querySelector('.confirm-dialog')`); await confirm('删除备份'); await idle()
        assert.equal(await run(`document.querySelectorAll('.memory-backup-row').length`), 1)
        await run(`document.querySelector('[aria-label="关闭记忆备份"]').click()`)
      })
      await check('大文件分段阅读，不能保存截断内容', async () => {
        await select_file('large.txt'); await idle()
        assert.equal(await run(`[...document.querySelectorAll('.memory-toolbar button')].find(e=>e.textContent==='编辑').disabled`), true)
        assert.ok((await run(`document.querySelector('.memory-body').textContent.length`)) < 300000)
        await click('下一段'); await idle(); assert.equal(await run(`document.querySelector('.memory-pagination').textContent.includes('第 2 段')`), true)
        await click('上一段'); await idle()
      })
      await check('未知格式仅显示元数据且 IPC 拒绝伪造路径', async () => {
        await select_file('other.json'); await idle()
        assert.equal(await run(`document.querySelector('.memory-detail').textContent.includes('other.json')`), true)
        assert.equal(await run(`!!document.querySelector('[aria-label="记忆编辑器"]')`), false)
        const forged = await run(`window.codexMemories.read(${JSON.stringify(summary_path)})`)
        assert.equal(forged.success, false)
      })
      fs.writeFileSync(summary_path, original_summary)
      await click('刷新'); await idle()
      await select_file('memory_summary.md'); await idle()
      await check('浅色、深色、高对比主题及窄窗口分类下拉', async () => {
        for (const theme of ['light', 'dark', 'high-contrast']) {
          await run(`document.querySelector('.app-shell').className='app-shell theme-${theme}'`)
          await run('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')
          fs.writeFileSync(path.join(report_root, `memory-${theme}-20260920.png`), (await window.webContents.capturePage()).toPNG())
          assert.equal(await run(`document.querySelector('.memory-workbench').scrollWidth <= document.querySelector('.memory-workbench').clientWidth + 1`), true)
        }
        window.setContentSize(960, 760)
        await run('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))')
        assert.equal(await run(`getComputedStyle(document.querySelector('.memory-categories')).display`), 'none')
        assert.notEqual(await run(`getComputedStyle(document.querySelector('.memory-mobile-category')).display`), 'none')
        assert.equal(await run(`document.documentElement.scrollWidth <= innerWidth`), true)
        fs.writeFileSync(path.join(report_root, 'memory-narrow-20260920.png'), (await window.webContents.capturePage()).toPNG())
      })
      assert.deepEqual(console_errors, [])
      results.push('渲染控制台零错误')
      fs.writeFileSync(path.join(report_root, 'memory-ui-result-20260920.json'), JSON.stringify({ passed: results.length, results, console_errors, sandbox }, null, 2))
      console.log(`记忆页面验证完成：${results.length} 项通过；隔离目录：${sandbox}`)
      clearTimeout(timeout); app.exit(0)
    } catch (error) {
      console.error(error)
      fs.writeFileSync(path.join(report_root, 'memory-ui-failure-20260920.png'), (await window.webContents.capturePage()).toPNG())
      fs.writeFileSync(path.join(report_root, 'memory-ui-failure-20260920.json'), JSON.stringify({ passed: results, error: String(error), sandbox }, null, 2))
      clearTimeout(timeout); app.exit(1)
    }
  })
})
require('../out/main/index.js')
