// 使用隔离的 CODEX_HOME 验证真实 preload、项目列表、会话详情和消息块选择。
const { app, BrowserWindow, dialog } = require('electron')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const assert = require('node:assert/strict')

const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'codex-manager-session-ui-'))
const app_data = path.join(sandbox, 'app-data')
const bootstrap = path.join(sandbox, 'bootstrap')
const codex = path.join(sandbox, '.codex')
const session_file = path.join(codex, 'sessions', '2026', '09', '18', 'rollout-ui-session.jsonl')
const export_path = path.join(sandbox, 'session-export.md')
fs.mkdirSync(app_data); fs.mkdirSync(bootstrap); fs.mkdirSync(path.join(codex, 'sessions', '2026', '09', '18'), { recursive: true })
app.setPath('appData', app_data); app.setPath('userData', bootstrap); app.setPath('sessionData', bootstrap)
process.env.CODEX_HOME = codex
const json = value => JSON.stringify(value)
const rows = [
  { timestamp: '2026-09-18T01:00:00Z', type: 'session_meta', payload: { id: 'ui-session', cwd: 'D:/workspace/ui-fixture' } },
  { timestamp: '2026-09-18T01:00:01Z', type: 'response_item', payload: { type: 'message', role: 'user', content: [{ type: 'input_text', text: '检查 UI fixture' }] } },
  { timestamp: '2026-09-18T01:00:02Z', type: 'response_item', payload: { type: 'message', role: 'assistant', content: [{ type: 'output_text', text: 'fixture 正常' }] } },
  { timestamp: '2026-09-18T01:00:03Z', type: 'response_item', payload: { type: 'custom_tool_call', call_id: 'ui-tool', name: 'exec_command', input: '{"cmd":"pwd"}' } },
  { timestamp: '2026-09-18T01:00:04Z', type: 'response_item', payload: { type: 'custom_tool_call_output', call_id: 'ui-tool', output: 'D:/workspace/ui-fixture' } },
]
for (let i = 0; i < 120; i++) rows.push({ type: 'response_item', payload: { type: 'message', role: 'user', content: `分页问题${i}` } }, { type: 'response_item', payload: { type: 'message', role: 'assistant', content: '独立滚动验证\n'.repeat(12) } })
fs.writeFileSync(session_file, rows.map(json).join('\n') + '\n')
for (let i = 0; i < 60; i++) {
  const id = `other-${i}`
  const cwd = i < 30 ? 'D:/workspace/ui-fixture' : i === 59 ? 'D:/workspace/project-with-a-deliberately-long-title-that-can-be-dragged-horizontally' : `D:/workspace/project-${i}`
  fs.writeFileSync(path.join(codex, 'sessions', '2026', '09', '18', `rollout-${id}.jsonl`), [
    { type: 'session_meta', payload: { id, cwd } },
    { type: 'response_item', payload: { type: 'message', role: 'user', content: i === 59 ? '这是一个用于验证鼠标左右拖动查看完整标题的超长会话标题内容' : `其他会话标记${i}` } },
  ].map(json).join('\n'))
}
fs.writeFileSync(path.join(codex, 'sessions', '2026', '09', '18', 'rollout-unassigned.jsonl'), [
  { type: 'session_meta', payload: { id: 'unassigned' } },
  { type: 'response_item', payload: { type: 'message', role: 'user', content: '未归属会话' } },
].map(json).join('\n'))
let canceled = false
let suggested_path = ''
dialog.showSaveDialog = async (_window, options) => { suggested_path = options.defaultPath; return { canceled, filePath: export_path } }
dialog.showMessageBox = async () => ({ response: 0 })

const timeout = setTimeout(() => { console.error('会话页面验证超时'); app.exit(2) }, 30000)
app.once('browser-window-created', (_event, window) => window.webContents.once('did-finish-load', async () => {
  try {
    window.setContentSize(1600, 900)
    const run = code => window.webContents.executeJavaScript(code, true).catch(error => { console.error('执行脚本失败：', code, error); throw error })
    const until = async code => { for (let i = 0; i < 100; i++) { if (await run(code)) return; await new Promise(resolve => setTimeout(resolve, 50)) }; throw Error(`等待条件超时：${code}`) }
    const catalog = await run('window.codexAccounts.sessions.list()')
    assert.equal(catalog.success, true); assert.equal(catalog.data.sessions.length, 62); assert.equal(catalog.data.projects.find(item => item.name === 'ui-fixture').sessionCount, 31)
    await run("document.querySelector('nav button[aria-label=\\\"会话管理\\\"]').click()")
    await until('!!document.querySelector(".sessions-workbench")')
    const project_order = await run('[...document.querySelectorAll(".project-row")].map(button => button.textContent.trim())')
    assert.equal(project_order[0].includes('全部项目'), true)
    assert.equal(project_order[1].includes('未归属项目'), true, '未归属项目必须紧跟全部项目')
    assert.equal(await run('document.querySelector(".session-row input") === null'), true, '会话列表不提供会话级勾选')
    assert.equal(await run('document.querySelector(".session-filter") === null'), true, '会话列表不显示归档筛选勾选框')
    assert.equal(await run('document.querySelectorAll(".session-divider").length'), 2, '两栏交界处必须有可拖动分隔线')
    const frame = () => run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
    await frame()
    const widths = () => run('[...document.querySelectorAll(".session-projects,.session-list,.session-detail")].map(pane => pane.getBoundingClientRect().width)')
    const drag_divider = async (index, delta) => {
      const before = await widths()
      const point = await run(`(() => { const r = document.querySelectorAll('.session-divider')[${index}].getBoundingClientRect(); return { x: Math.round(r.x + r.width / 2), y: Math.round(r.y + r.height / 2) } })()`)
      const target_x = Math.max(30, Math.min(window.getContentSize()[0] - 30, point.x + delta))
      window.focus()
      window.webContents.sendInputEvent({ type: 'mouseMove', ...point })
      window.webContents.sendInputEvent({ type: 'mouseDown', ...point, button: 'left', clickCount: 1 })
      await until('document.querySelector(".sessions-workbench").classList.contains("is-resizing")')
      window.webContents.sendInputEvent({ type: 'mouseMove', button: 'left', modifiers: ['leftbuttondown'], x: target_x, y: point.y, movementX: delta, movementY: 0 })
      const direction = delta >= 0 ? 1 : -1
      if (Math.abs(delta) < 200) await until(`(${direction} * (document.querySelectorAll('.session-projects,.session-list,.session-detail')[${index}].getBoundingClientRect().width - ${before[index]})) > 1`)
      else await until(`document.querySelectorAll('.session-projects,.session-list,.session-detail')[${index}].getBoundingClientRect().width >= ${[160, 220][index]}`)
      window.webContents.sendInputEvent({ type: 'mouseUp', x: target_x, y: point.y, button: 'left', clickCount: 1 })
      await until('!document.querySelector(".sessions-workbench").classList.contains("is-resizing")')
      assert.equal(await run('document.querySelector(".sessions-workbench").classList.contains("is-resizing")'), false, '松开后必须结束调整宽度')
    }
    for (const index of [0, 1]) {
      const before = await widths()
      assert.equal(await run(`getComputedStyle(document.querySelectorAll('.session-divider')[${index}]).cursor`), 'col-resize')
      await drag_divider(index, 60)
      const expanded = await widths()
      assert.ok(expanded[index] > before[index] + 50, '向右拖动应展开左侧面板')
      assert.ok(expanded[index + 1] < before[index + 1] - 50, '相邻面板应同步收窄')
      assert.ok(Math.abs(expanded[2 - index * 2] - before[2 - index * 2]) < 2, '非相邻面板应保持宽度')
      await drag_divider(index, -60)
      const restored = await widths()
      assert.ok(Math.abs(restored[index] - before[index]) < 2, '向左拖动应恢复原来的栏宽')
    }
    const keyboard_before = await widths()
    await run('document.querySelector(".session-divider").focus()')
    window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Right' })
    window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Right' })
    await until(`document.querySelector('.session-projects').getBoundingClientRect().width > ${keyboard_before[0] + 19}`)
    window.webContents.sendInputEvent({ type: 'keyDown', keyCode: 'Left' })
    window.webContents.sendInputEvent({ type: 'keyUp', keyCode: 'Left' })
    await until(`Math.abs(document.querySelector('.session-projects').getBoundingClientRect().width - ${keyboard_before[0]}) < 2`)
    await drag_divider(0, -500)
    assert.ok((await widths())[0] >= 159, '极限拖动不能把项目面板挤没')
    await drag_divider(1, 900)
    assert.ok((await widths())[2] >= 239, '极限拖动必须保留详情区域')
    await run('document.querySelector(".sessions-workbench").removeAttribute("style")')
    await frame()
    await run(`[...document.querySelectorAll('.project-row')].find(button => button.textContent.includes('ui-fixture')).click()`)
    await run(`[...document.querySelectorAll('.session-row-main')].find(button => button.textContent.includes('检查 UI fixture')).click()`)
    await until('!!document.querySelector(".session-detail-head")')
    assert.equal(await run('document.querySelector(".message-text").textContent.includes("检查 UI fixture")'), true)
    assert.equal(await run('document.querySelector(".session-selection-bar") === null'), true, '打开会话后默认不显示选择栏')
    assert.equal(await run('document.querySelector(".message-check") === null'), true, '打开会话后默认不显示消息选择框')
    assert.equal(await run('document.querySelectorAll(".export-scope").length'), 0)
    assert.equal(await run('document.querySelector(".message-tools") !== null'), true)
    const scroll = await run(`(() => {
      const pane = document.querySelector('.session-timeline'); pane.scrollTop = 500;
      return { detail: pane.scrollTop, outer: document.querySelector('.content').scrollTop, projects: document.querySelector('.session-projects').scrollTop, list: document.querySelector('.session-list').scrollTop,
        bounded: document.querySelector('.sessions-workbench').getBoundingClientRect().bottom <= innerHeight }
    })()`)
    assert.ok(scroll.detail > 0, '详情必须在独立容器内滚动')
    assert.equal(scroll.outer, 0); assert.equal(scroll.projects, 0); assert.equal(scroll.list, 0); assert.equal(scroll.bounded, true)
    for (const selector of ['.session-projects', '.session-list']) {
      const isolated = await run(`(() => { const pane = document.querySelector('${selector}'); pane.scrollTop = 150; return { top: pane.scrollTop, outer: document.querySelector('.content').scrollTop, detail: document.querySelector('.session-timeline').scrollTop } })()`)
      assert.ok(isolated.top > 0, `${selector}必须可独立滚动`); assert.equal(isolated.outer, 0); assert.equal(isolated.detail, scroll.detail)
    }
    await run(`['.session-projects','.session-list','.session-timeline'].forEach(selector => document.querySelector(selector).scrollTop = 0)`)
    await frame()
    const point = await run(`(() => { const r = document.querySelector('.session-timeline').getBoundingClientRect(); return { x: Math.floor(r.x + r.width / 2), y: Math.floor(r.y + r.height / 2) } })()`)
    window.focus()
    window.webContents.sendInputEvent({ type: 'mouseMove', ...point })
    window.webContents.sendInputEvent({ type: 'mouseWheel', ...point, deltaY: -300, deltaX: 0, wheelTicksY: -3, wheelTicksX: 0 })
    await until('document.querySelector(".session-timeline").scrollTop > 0')
    assert.equal(await run('document.querySelector(".content").scrollTop + document.querySelector(".session-projects").scrollTop + document.querySelector(".session-list").scrollTop'), 0)
    const detail_button = text => run(`[...document.querySelectorAll('.session-detail-head button')].find(button => button.textContent.trim() === ${JSON.stringify(text)}).click()`)
    await detail_button('删除会话记忆')
    await until('document.querySelector(".session-selection-bar") !== null')
    assert.ok(await run('document.querySelectorAll(".message-check").length > 0'), '进入删除记忆模式后显示消息选择框')
    await run('document.querySelector(".message-check input").click()')
    assert.equal(await run('document.querySelector(".session-selection-bar").textContent.includes("已选 1 个消息块")'), true)
    const before_delete = fs.readFileSync(session_file, 'utf8')
    await detail_button('删除会话记忆')
    await until('document.querySelector(".delete-dialog")')
    assert.ok(await run('document.querySelector(".delete-dialog").textContent.includes("修改本地 Session 文件")'))
    assert.ok(await run('document.querySelector(".delete-dialog").textContent.includes("Codex 本地记忆")'))
    await run('[...document.querySelectorAll(".delete-dialog button")].find(button => button.textContent.trim() === "取消").click()')
    assert.equal(fs.readFileSync(session_file, 'utf8'), before_delete, '取消删除不能修改源文件')
    await detail_button('删除会话记忆')
    await until('document.querySelector(".delete-dialog")')
    fs.appendFileSync(session_file, json({ type: 'event_msg', payload: { type: 'token_count' } }) + '\n')
    const externally_changed = fs.readFileSync(session_file, 'utf8')
    await run('[...document.querySelectorAll(".delete-dialog button")].find(button => button.textContent.trim() === "确认删除记忆").click()')
    await until('document.querySelector(".session-notice.error")?.textContent.includes("删除未完成")')
    assert.equal(await run('document.querySelector(".delete-dialog") === null'), true, '失败通知必须可见，不能被弹框遮挡')
    assert.ok(await run('document.querySelector(".message-check input").checked'), '失败必须保留选择')
    assert.equal(fs.readFileSync(session_file, 'utf8'), externally_changed, '冲突失败不能修改外部新内容')
    fs.writeFileSync(session_file, before_delete)
    await detail_button('删除会话记忆')
    await until('document.querySelector(".delete-dialog")')
    await run('[...document.querySelectorAll(".delete-dialog button")].find(button => button.textContent.trim() === "确认删除记忆").click()')
    await until('document.querySelector(".session-notice.success")?.textContent.includes("成功删除")')
    assert.equal(await run('document.querySelector(".delete-dialog") === null'), true, '删除成功后确认弹框必须关闭')
    const deleted_content = fs.readFileSync(session_file, 'utf8')
    assert.ok(!deleted_content.includes('检查 UI fixture')); assert.ok(deleted_content.includes('分页问题0'))
    await until('(() => { const button = [...document.querySelectorAll(".session-detail-head button")].find(button => button.textContent.trim() === "备份"); return !!button && !button.disabled })()')
    await detail_button('备份')
    await until('document.querySelector(".backup-list")')
    assert.ok(await run('document.querySelector(".backup-list").textContent.includes("1 个轮次")'))
    await run(`document.querySelector('[aria-label="关闭会话删除备份"]').click()`)
    await run('document.querySelector(".session-undo button").click()')
    await until('document.querySelector(".session-notice")?.textContent.includes("已撤销删除")')
    assert.equal(fs.readFileSync(session_file, 'utf8'), before_delete, '立即撤销应恢复原始 Session 文件')
    assert.ok(await run('document.querySelector(".session-selection-bar").textContent.includes("已选 1 个消息块")'))
    const initial_count = await run('document.querySelectorAll(".message-block").length')
    await run(`[...document.querySelectorAll('.session-timeline button')].find(button => button.textContent.includes('加载更多')).click()`)
    await until(`document.querySelectorAll('.message-block').length > ${initial_count}`)
    assert.equal(await run('document.querySelector(".message-check input").checked'), true)
    const click_text = text => run(`[...document.querySelectorAll('[role="dialog"] button')].find(button => button.textContent.trim() === ${JSON.stringify(text)}).click()`)
    await run('document.querySelector(".session-detail-head button").click()')
    await until('document.querySelectorAll(".export-scope").length === 4')
    await run('document.querySelectorAll(".export-scope")[0].click()')
    await click_text('导出 Markdown')
    await until('!document.querySelector(".export-scope")')
    let markdown = fs.readFileSync(export_path, 'utf8')
    assert.ok(markdown.includes('检查 UI fixture')); assert.ok(!markdown.includes('fixture 正常')); assert.ok(!markdown.includes('分页问题'))
    assert.ok(suggested_path.includes('ui-fixture-检查 UI fixture'))
    await run(`[...document.querySelectorAll('.session-selection-bar button')].find(button => button.textContent === '清空').click()`)
    await run('document.querySelector(".session-detail-head button").click()')
    await until('document.querySelectorAll(".export-scope").length === 4')
    await run('document.querySelectorAll(".export-scope")[2].click()')
    await click_text('导出 Markdown')
    await until('!document.querySelector(".export-scope")')
    markdown = fs.readFileSync(export_path, 'utf8')
    assert.ok(markdown.includes('exec_command')); assert.ok(markdown.includes('分页问题119')); assert.ok(!markdown.includes('其他会话标记'))
    await run(`[...document.querySelectorAll('.page-head button')].find(button => button.textContent.trim() === '导出').click()`)
    await until('document.querySelectorAll(".export-scope").length === 4')
    await click_text('导出 Markdown')
    await until('!document.querySelector(".export-scope")')
    assert.ok(fs.readFileSync(export_path, 'utf8').includes('其他会话标记29'))
    canceled = true
    await run('document.querySelector(".session-detail-head button").click()')
    await until('document.querySelectorAll(".export-scope").length === 4')
    await click_text('导出 Markdown')
    await until('document.querySelector(".session-notice")?.textContent.includes("已取消导出")')
    await drag_divider(0, 40)
    await drag_divider(1, 40)
    for (const width of [1600, 1280, 920]) {
      window.setContentSize(width, 900)
      await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
      assert.ok(await run('document.querySelector(".session-timeline").clientHeight > 0'))
      assert.ok(await run('document.querySelector(".content").scrollHeight <= document.querySelector(".content").clientHeight + 1'))
      assert.ok(await run('document.querySelector(".sessions-workbench").scrollWidth <= document.querySelector(".sessions-workbench").clientWidth + 1'), '调整栏宽后缩小窗口不能产生横向溢出')
      assert.equal(await run('[...document.querySelectorAll(".session-projects,.session-list,.session-timeline")].every(pane => getComputedStyle(pane).scrollbarWidth === "thin")'), true, '三栏滚动条应显示为细滚动条')
    }
    window.setContentSize(1600, 900)
    await run('[...document.querySelectorAll(".session-projects,.session-list,.session-timeline")].forEach(pane => { pane.scrollTop = 0; pane.scrollLeft = 0 })')
    await run('new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve)))')
    const screenshot = path.resolve(__dirname, '../reports/session-ui-20260918.png')
    fs.writeFileSync(screenshot, (await window.webContents.capturePage()).toPNG())
    console.log('会话页面验证通过：两处分隔线真实鼠标伸缩、最小宽度、键盘调整、细滚动条、三栏独立滚轮、分页保留选择、部分/完整/项目实际导出、文件名、取消和三种窗口宽度均正确。')
    clearTimeout(timeout); window.destroy(); app.exit(0)
  } catch (error) { console.error('会话页面验证失败：', error); app.exit(1) }
}))
require(path.resolve(__dirname, '../out/main/index.js'))
