import { contextBridge, ipcRenderer } from 'electron'
import type { MemoryApi } from '../shared/memory_types'

const memory_api: MemoryApi = {
  list: () => ipcRenderer.invoke('memories:list'),
  refresh: () => ipcRenderer.invoke('memories:refresh'),
  search: (query, category) => ipcRenderer.invoke('memories:search', query, category),
  read: (id, offset, expected_version) => ipcRenderer.invoke('memories:read', id, offset, expected_version),
  create: input => ipcRenderer.invoke('memories:create', input),
  save: input => ipcRenderer.invoke('memories:save', input),
  remove: input => ipcRenderer.invoke('memories:remove', input),
  list_backups: () => ipcRenderer.invoke('memories:list_backups'),
  read_backup: (id, offset) => ipcRenderer.invoke('memories:read_backup', id, offset),
  restore: id => ipcRenderer.invoke('memories:restore', id),
  remove_backup: id => ipcRenderer.invoke('memories:remove_backup', id),
}
contextBridge.exposeInMainWorld('codexMemories', memory_api)
contextBridge.exposeInMainWorld('codexAccounts', {
  list: () => ipcRenderer.invoke('accounts:list'), importText: (raw: string) => ipcRenderer.invoke('accounts:importText', raw), importFile: () => ipcRenderer.invoke('accounts:importFile'), importLocal: () => ipcRenderer.invoke('accounts:importLocal'), confirmImport: (preview_id: string) => ipcRenderer.invoke('accounts:confirmImport', preview_id), cancelImport: (preview_id: string) => ipcRenderer.invoke('accounts:cancelImport', preview_id), activate: (id: string) => ipcRenderer.invoke('accounts:activate', id), refresh: (id: string) => ipcRenderer.invoke('accounts:refresh', id), refreshAll: () => ipcRenderer.invoke('accounts:refreshAll'), remove: (id: string) => ipcRenderer.invoke('accounts:remove', id), removeMany: (ids: string[]) => ipcRenderer.invoke('accounts:removeMany', ids), export: (ids: string[]) => ipcRenderer.invoke('accounts:export', ids), getSettings: () => ipcRenderer.invoke('settings:get'), saveSettings: (settings: unknown) => ipcRenderer.invoke('settings:save', settings), promptGet: () => ipcRenderer.invoke('prompt:get'), promptSave: (content: string) => ipcRenderer.invoke('prompt:save', content), promptReset: () => ipcRenderer.invoke('prompt:reset'), info: () => ipcRenderer.invoke('app:info'), onChanged: (callback: () => void) => { const listener = (): void => callback(); ipcRenderer.on('accounts:changed', listener); return () => ipcRenderer.removeListener('accounts:changed', listener) }
  , promptPresets: () => ipcRenderer.invoke('prompt:presets'), promptExport: () => ipcRenderer.invoke('prompt:export'), promptImport: () => ipcRenderer.invoke('prompt:import'), sessions: { list: () => ipcRenderer.invoke('sessions:list'), detail: (id: string, cursor?: import('../shared/types').SessionCursor) => ipcRenderer.invoke('sessions:detail', id, cursor), refresh: () => ipcRenderer.invoke('sessions:refresh'), export: (request: unknown) => ipcRenderer.invoke('sessions:export', request), deletePreview: (input: import('../shared/types').SessionDeleteRequest | { sessionId: string; selectedBlockIds: string[] }) => ipcRenderer.invoke('sessions:deletePreview', input), delete: (request: import('../shared/types').SessionDeleteRequest) => ipcRenderer.invoke('sessions:delete', request), backups: (sessionId?: string) => ipcRenderer.invoke('sessions:backups', sessionId), restore: (operationId: string) => ipcRenderer.invoke('sessions:restore', operationId), removeBackup: (operationId: string) => ipcRenderer.invoke('sessions:backupDelete', operationId) }
})
contextBridge.exposeInMainWorld('codexExtensions', { info: () => ipcRenderer.invoke('extensions:info'), skills: () => ipcRenderer.invoke('skills:list'), skillDetail: (path: string) => ipcRenderer.invoke('skills:detail', path), setSkillEnabled: (path: string, enabled: boolean) => ipcRenderer.invoke('skills:setEnabled', path, enabled), importSkill: () => ipcRenderer.invoke('skills:import'), exportSkills: (paths: string[]) => ipcRenderer.invoke('skills:export', paths), mcp: () => ipcRenderer.invoke('mcp:list'), mcpDetail: (name: string) => ipcRenderer.invoke('mcp:detail', name), setMcpEnabled: (name: string, enabled: boolean) => ipcRenderer.invoke('mcp:setEnabled', name, enabled), saveMcp: (name: string, value: unknown) => ipcRenderer.invoke('mcp:save', name, value), removeMcp: (name: string) => ipcRenderer.invoke('mcp:remove', name), mcpBackups: () => ipcRenderer.invoke('mcp:backups'), mcpDiff: (name: string) => ipcRenderer.invoke('mcp:diff', name), rollbackMcp: (name: string) => ipcRenderer.invoke('mcp:rollback', name), importMcpJson: (raw: string) => ipcRenderer.invoke('mcp:importJson', raw), importMcpFile: () => ipcRenderer.invoke('mcp:importFile'), exportMcpJson: () => ipcRenderer.invoke('mcp:exportJson'), exportMcpToml: () => ipcRenderer.invoke('mcp:exportToml') })
contextBridge.exposeInMainWorld('codexSkins', { status: () => ipcRenderer.invoke('skins:status'), backup: () => ipcRenderer.invoke('skins:backup'), removeBackup: (id: string) => ipcRenderer.invoke('skins:removeBackup', id), apply: (id: string) => ipcRenderer.invoke('skins:apply', id), restore: (id: string) => ipcRenderer.invoke('skins:restore', id), launch: () => ipcRenderer.invoke('skins:launch'), setMotion: (enabled: boolean) => ipcRenderer.invoke('skins:setMotion', enabled), list: () => ipcRenderer.invoke('skins:list'), preview: (id: string) => ipcRenderer.invoke('skins:preview', id), renderPreview: (id: string, mode: 'light' | 'dark', view: 'home' | 'task' | 'settings' | 'components', motion_enabled: boolean) => ipcRenderer.invoke('skins:renderPreview', id, mode, view, motion_enabled), export: (id: string) => ipcRenderer.invoke('skins:export', id) })
