import type { SkinMode, SkinPreviewView } from '../shared/skins'
import { component_preview_html } from './theme_component_preview'

const escape_html = (value: string): string => value.replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!)
const icon = (path: string): string => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`
const plus = icon('M12 4v16M4 12h16')
const arrow = icon('m7 12 5-5 5 5M12 7v12')

// 固定的原生界面示例，仅补充宿主布局；所有主题效果由实际应用引擎注入。
export function theme_preview_html(config: { id: string; name: string; tagline: string; description: string; codexManager?: { ui_revision?: 1 } }, mode: SkinMode, view: SkinPreviewView, payload: string): string {
  if (config.codexManager?.ui_revision === 1) return component_preview_html(config, mode, view, payload)
  const scene = view === 'home'
    ? `<div class="preview-native-home" role="main"><div><div><div class="preview-welcome"><span class="preview-eyebrow">${escape_html(config.name)}</span><h1>${escape_html(config.tagline)}</h1><p>${escape_html(config.description)}</p></div><div class="group/home-suggestions preview-suggestions"><button>${plus}<span>探索项目</span></button><button>${icon('m5 12 4 4L19 6')}<span>检查代码</span></button></div><div class="composer-surface-chrome"><div class="ProseMirror" contenteditable="true" aria-label="向 Codex 提问">描述你要完成的任务</div><div class="preview-composer-footer"><span>${plus}添加上下文</span><button aria-label="发送示例">${arrow}</button></div></div><p class="preview-hint">从一个想法开始，让 Codex 帮你继续。</p></div></div></div>`
    : `<div class="preview-native-task" role="main"><header class="preview-task-header"><span>主题预览</span><span class="preview-eyebrow">示例会话</span></header><section class="thread-scroll-container"><div class="preview-user" data-message-author-role="user">请检查主题在长中文、代码和终端中的阅读效果。</div><article data-message-author-role="assistant"><h1>让每一行内容都清楚</h1><p>界面装饰退到阅读区域之外，正文保持稳定的底色。无论是梳理想法、阅读长段中文，还是检查实现细节，都能自然地找到重点。</p><pre><code><span class="preview-code-comment">// 沿用原生等宽字体与字号偏好</span>\nconst theme = await load_skin('fruit-base')\nreturn { ...theme, mode: 'dark' }</code></pre><pre class="diff"><code><span>− 依赖远程主题图片</span>\n<span>+ 使用完整的本地主题素材</span>\n<span>+ 保持正文与界面状态清晰</span></code></pre><div class="terminal"><span>终端 · PowerShell</span><pre>PS&gt; pnpm test\n✓ 示例任务检查完成</pre></div><p>下一步可以继续检查选中态、焦点边界与对话框层次。</p></article></section><div class="composer-surface-chrome"><div class="ProseMirror" contenteditable="true" aria-label="继续对话">继续询问</div><div class="preview-composer-footer"><span>${plus}添加上下文</span><button aria-label="发送示例">${arrow}</button></div></div></div>`
  return `<!doctype html><html class="${mode}" data-theme="${mode}" data-appearance="${mode}"><head><meta charset="utf-8"><meta http-equiv="Content-Security-Policy" content="default-src 'none';img-src data: blob:;style-src 'unsafe-inline';script-src 'unsafe-inline';font-src 'none';connect-src 'none';object-src 'none';frame-src 'none';base-uri 'none';form-action 'none'"><meta name="viewport" content="width=device-width,initial-scale=1"><style>
*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Segoe UI,Microsoft YaHei UI,sans-serif;font-size:14px}body{background:var(--ds-bg,#f6f8fc);color:var(--ds-text,#172033)}button{font:inherit;cursor:default}svg{width:18px;height:18px;fill:none;stroke:currentColor;stroke-width:1.6;flex-shrink:0}
.preview-shell{display:grid;grid-template-columns:208px minmax(0,1fr);min-height:100vh}.app-shell-left-panel{padding:28px 16px;border-right:1px solid var(--ds-line);background:var(--ds-panel)}.main-surface{position:relative;min-width:0;padding:60px 48px 32px;z-index:1}.preview-native-home,.preview-native-task{max-width:780px;margin:0 auto}.preview-native-home{padding-top:50px}.preview-welcome{max-width:500px}.preview-eyebrow{color:var(--ds-muted);font-size:12px;letter-spacing:1px}.preview-welcome h1{font-size:30px;line-height:1.4;letter-spacing:-.6px;max-width:500px;margin:18px 0}.preview-welcome p{color:var(--ds-muted);line-height:1.8;max-width:450px}.preview-suggestions{display:flex;gap:12px;margin-top:36px}.composer-surface-chrome{margin-top:20px;padding:20px;border:1px solid var(--ds-line);border-radius:var(--ds-radius);background:var(--ds-panel)}.ProseMirror{min-height:36px;line-height:1.7}.preview-composer-footer{display:flex;justify-content:space-between;align-items:center;margin-top:16px;font-size:12px;color:var(--ds-muted)}.preview-composer-footer>span{display:flex;align-items:center;gap:6px}.preview-composer-footer button{display:grid;place-items:center;width:30px;height:30px;padding:4px;border:1px solid var(--ds-line);border-radius:50%;background:var(--ds-bg);color:var(--ds-text)}.preview-hint{color:var(--ds-muted);font-size:12px;margin:16px 0}.preview-project-label{color:var(--ds-muted);font-size:11px;margin:36px 10px 10px}.preview-project{padding:9px 10px;font-size:13px;color:var(--ds-muted)}.preview-task-header{display:flex;justify-content:space-between;padding-bottom:16px;border-bottom:1px solid var(--ds-line)}.preview-user{margin:24px 0 28px 15%;background:var(--ds-panel-2,var(--ds-panel));border:1px solid var(--ds-line);padding:14px 18px;border-radius:12px;line-height:1.7}.preview-native-task article{line-height:1.8}.preview-native-task h1{font-size:22px;margin:20px 0 12px}.preview-native-task pre{overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;padding:16px;border:1px solid var(--ds-line);border-radius:8px;background:var(--ds-panel);font:12px/1.8 Consolas,monospace}.preview-code-comment{color:var(--ds-muted)}.terminal>span{font-size:11px;color:var(--ds-muted)}.terminal pre{margin-top:8px}.diff{color:var(--ds-text)}
html.codex-dream-skin body .preview-nav{display:flex!important;flex-direction:column!important;gap:5px!important}html.codex-dream-skin body :is(.preview-brand,.preview-nav button,.preview-suggestions button){display:flex!important;align-items:center!important;gap:10px!important;padding:10px 12px!important;color:var(--ds-text)!important;background:var(--ds-panel)!important;border:1px solid var(--ds-line)!important;border-radius:var(--ds-radius)!important;text-align:left!important;box-shadow:none!important;transform:none!important}html.codex-dream-skin body .preview-brand{font-size:19px!important;font-weight:650!important;margin-bottom:24px!important;border:0!important;padding:0 10px!important}html.codex-dream-skin body .preview-nav button{border-color:transparent!important}html.codex-dream-skin body .preview-nav button:first-child{border-color:var(--ds-line)!important}html.codex-dream-skin body :is(.preview-brand,.preview-nav,.preview-suggestions,.preview-composer-footer) svg{width:18px!important;height:18px!important;background:none!important;padding:0!important;fill:none!important;stroke:currentColor!important}html.codex-dream-skin body :is(.preview-brand,.preview-nav,.preview-suggestions,.preview-composer-footer) svg path{fill:none!important;stroke:currentColor!important}
@media(max-width:960px){.preview-shell{grid-template-columns:170px minmax(0,1fr)}.main-surface{padding:36px 28px}.preview-native-home{padding-top:30px}.preview-welcome h1{font-size:26px}}@media(max-width:680px){.preview-shell{grid-template-columns:120px minmax(0,1fr)}.app-shell-left-panel{padding:20px 8px}.main-surface{padding:26px 20px}.preview-welcome h1{font-size:22px}.preview-suggestions{flex-wrap:wrap}.preview-project{font-size:11px}}
</style></head><body data-preview-view="${view}"><div class="preview-shell"><aside class="app-shell-left-panel"><div class="preview-brand">${icon('M5 5h14v14H5zM9 9h6M9 13h4')}Codex</div><nav class="preview-nav"><button>${plus}新任务</button><button>${icon('M4 6h16v14H4zM8 3v6M16 3v6')}任务</button><button>${icon('M5 12h14M12 5v14')}自动化</button></nav><div class="preview-project-label">项目</div><div class="preview-project">⌁　我的工作空间</div><div class="preview-project">　　设计与实现</div><div class="preview-project">　　代码检查</div></aside><main class="main-surface" role="main"><div class="_MainContentFrame_preview"><div class="_MainContentViewport_preview">${scene}</div></div></main></div><script>${payload.replace(/<\/script/gi, '<\\/script')};document.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();parent.postMessage({type:'original-preview-close'},'*')}if(event.key==='Tab'){event.preventDefault();parent.postMessage({type:'original-preview-tab',backwards:event.shiftKey},'*')}});</script></body></html>`
}
